---
- hosts: ubuntu
  become: yes
  tasks: 
  - name: this will install apache server
    apt:
      name: apache2
      state: present
  - name: this will enable apache server
    service:
      name: apache2
      state: started
