---

- hosts: all
  become: yes
  gather_facts: True
  tasks:
  - name: install apache on ubuntu
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
  - name: install apache on redhat
    yum:
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"
  - service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_os_family == "RedHat"
