---
- hosts: redhat
  become: yes
  vars:
    jdk_dir: 8u131-b11
    jdk_archive: jdk-8u181-linux-x64.tar.gz
    jdk_local_dir: jdk1.8.0_131
    download_folder: /home/ansible
    bin_dir: /usr/bin
    profile_path: /etc/profile.d
    java_name: "{{ download_folder }}/{{ jdk_local_dir }}"
    java_archive: "{{ download_folder }}/{{ jdk_archive }}"
    download_url: http://download.oracle.com/otn-pub/java/jdk/{{jdk_dir}}/{{jdk_archive}}
    java_version: 8
    java_subversion: 131
    java_build_custom: 11
    jdk_version_detail_custom: "{{ java_version }}u{{ java_subversion }}-b{{ java_build_custom }}"
    jdk_tarball_hash: d54c1d3a095b4ff2b6607d096fa80163
    jdk_tarball_url: https://www.dropbox.com/s/zw3p1ym52dv3sdv/jdk-8u181-linux-x64.tar.gz

  tasks:
  - name: install utilities in ubuntu
    apt:
      name: "{{ item }}"
      state: present
    with_items: ["{{ wget_version }}","{{ git_version }}","{{ unzip_version }}"]
    when: ansible_os_family == "Debian"
  - name: install utilities in redhat
    yum:
      name: "{{ item }}"
      state: present
    with_items: ["{{ wget_version }}","{{ git_version }}","{{ unzip_version }}"]
    when: ansible_os_family == "RedHat"
 
  - name: download java
    command: wget "{{ jdk_tarball_url }}"
    command: mv jdk-8u181-linux-x64.tar.gz /home/ansible/
    command: tar xvf jdk-8u181-linux-x64.tar.gz

  - name: unzip java file
    # command: "tar -xzvf {{java_archive}} -C {{download_folder}} creates={{java_name}}"
    action: shell tar -xzvf {{java_archive}} -C {{download_folder}}

  - name: Fix ownership
    file: 
      state=directory 
      path={{java_name}} 
      owner=root 
      group=root 
      recurse=yes

  - name: Set systemwide java env file under /etc/profile.d/
    set_fact: 
      remote_file_path={{profile_path}}/java.sh

  # Create a blank file
  - name: Create a new file {{profile_path}}/java.sh
    file: 
      path={{remote_file_path}} 
      state=touch
  # Copy /etc/profile.d/java.sh with content
  - copy:
      content: |
                #!/bin/bash
                export JDK_HOME={{ java_name }}
                export JAVA_HOME={{ java_name }}
                export JRE_HOME={{ java_name }}/jre
                export PATH=$PATH:{{ java_name }}/bin:{{ java_name }}/jre/bin
      dest: /etc/profile.d/java.sh

# Fix the executable permission
  - name: Set executable perission
    file: 
      path={{profile_path}}/java.sh 
      owner=root 
      group=root 
      mode=0555 
      state=file 
      recurse=no
  # Export the env on th fly to make system wide change
  - name: Source the file {{profile_path}}/java.sh
    action: shell source /etc/profile.d/java.sh
