---
- hosts: ubuntu
  become: yes
  tasks:
  - name: remove dir
    command: "rm -rf /var/logs"
    tags:
      - prep
  - name: create tomcat user
    user:
      name: tomcat
      state: present
  - name: installing tomcat
    apt:
      name: tomcat7
      state: present
      update_cache: yes
